# based on the glfw-rs .travis.yml
dist: trusty
language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

before_install:
  - sudo apt-get update -qq

install: sudo apt-get install cmake libxinerama-dev libxcursor-dev x11proto-randr-dev

script:
  - cargo build
  - cargo test

